[world]
name = "Zunno Game"
seed = "zunno_game"

[namespace]
default = "zunno_game"

[env]
# rpc_url = ""         # env: STARKNET_RPC_URL
# account_address = "" # env: DOJO_ACCOUNT_ADDRESS
# private_key = ""     # env: DOJO_PRIVATE_KEY
# world_address = "<World Address>"
